name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install pandoc
      run: |
          wget https://github.com/jgm/pandoc/releases/download/3.1.9/pandoc-3.1.9-linux-amd64.tar.gz
          tar xvzf pandoc-3.1.9-linux-amd64.tar.gz --strip-components 1 -C /usr/local/
    - name: make
      run: make all
